### ISSUE TITLE
ACH + MERV terminology

### ISSUE THREAD

**Issue by TheotherBiggles** [kawesomekhan/covid-indoor#31]
Recently I have been trying to get colleagues at my (Arts) university to use the app, many non-engineers will use the app.
A question that frequently came back was "what is ACH?" 
I think it would help general usability on the basic mode to have "ACH (air changes and hour)"

MERV is also a bit mysterious/unclear for basic, even when translated to "Minimum Efficiency Reporting Value". I wonder if this would be clearer if changed to:

None, Poor Quality, Good Quality, High Quality

**Comment by kawesomekhan** [comment]
Hi TheotherBiggles,

Apologies for the delayed response - this past month we've been busy refining the existing app due to increased traffic, along with developing an updated Advanced mode which will hopefully come out soon. 

We've specified ACH to be units of /hr. In general, however, we view the red text in the input tabs to be values that may be of interest to users more familiar with the technical aspects of the model. We'd like to keep the MERV rating easily available so those technical users will know what exactly the dropdown choices are modifying. 

-Kasim
