### ISSUE TITLE
Increase visibility and importance of "Filtration" information

### ISSUE THREAD

**Issue by coldcandor** [kawesomekhan/covid-indoor#35]
First off, awesome project!

When browsing the site, my first thought was "wait, you're saying it's actually OK to have people inside for long periods with air circulation?!"  When a coworker pointed me to the "filtration system" dropdown on the second tab.  I'd recommend making it extremely clear on the first page what filtration is selected, and its importance.  Pretty much everything else I feel is common sense, but I doubt very many people think about what filter their air circulation has installed, at least in this context.

**Comment by kawesomekhan** [comment]
Hi Eric,

Thank you! I apologize for the delayed response, this past month we've received a significant increase in traffic and thus have been pretty busy refining the app along with developing an new Advanced mode (coming soon), so I'm only getting around to answering these comments now.

We'd like to make the app as simple as possible (at least in Basic mode) so that the average user will be able to take away the key message of the app within 30 seconds or so. I'll see if we can make filtration more prominent without limiting ease-of-use.

-Kasim
